//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngdungWeb_KhachHang.DICHVU_ASMX_ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DICHVU_ASMX_.DICHVU_ASMXSoap")]
    public interface DICHVU_ASMXSoap {
        
        // CODEGEN: Generating message contract since element name ChuoiXmlTruyVan from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraCuuPhieuThuePhong", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongResponse TraCuuPhieuThuePhong(UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraCuuPhieuThuePhong", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongResponse> TraCuuPhieuThuePhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequest request);
        
        // CODEGEN: Generating message contract since element name DocDuLieu_PhieuThuePhongResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_PhieuThuePhong", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongResponse DocDuLieu_PhieuThuePhong(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_PhieuThuePhong", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongResponse> DocDuLieu_PhieuThuePhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequest request);
        
        // CODEGEN: Generating message contract since element name DocDuLieu_DangNhap_TiepTanResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_DangNhap_TiepTan", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanResponse DocDuLieu_DangNhap_TiepTan(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_DangNhap_TiepTan", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanResponse> DocDuLieu_DangNhap_TiepTanAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequest request);
        
        // CODEGEN: Generating message contract since element name DocDuLieu_DangNhap_QLKhuVucResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_DangNhap_QLKhuVuc", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucResponse DocDuLieu_DangNhap_QLKhuVuc(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_DangNhap_QLKhuVuc", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucResponse> DocDuLieu_DangNhap_QLKhuVucAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequest request);
        
        // CODEGEN: Generating message contract since element name DocDuLieu_DangNhap_QLKhachSanResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_DangNhap_QLKhachSan", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanResponse DocDuLieu_DangNhap_QLKhachSan(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_DangNhap_QLKhachSan", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanResponse> DocDuLieu_DangNhap_QLKhachSanAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequest request);
        
        // CODEGEN: Generating message contract since element name DocDuLieu_ThongTinPhongResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_ThongTinPhong", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongResponse DocDuLieu_ThongTinPhong(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_ThongTinPhong", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongResponse> DocDuLieu_ThongTinPhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequest request);
        
        // CODEGEN: Generating message contract since element name DocDuLieu_ThongKeDoanhThuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_ThongKeDoanhThu", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuResponse DocDuLieu_ThongKeDoanhThu(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_ThongKeDoanhThu", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuResponse> DocDuLieu_ThongKeDoanhThuAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequest request);
        
        // CODEGEN: Generating message contract since element name ChuoiPhieuThue_ from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GhiDuLieu_CapNhatPhieuThuePhong", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongResponse GhiDuLieu_CapNhatPhieuThuePhong(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GhiDuLieu_CapNhatPhieuThuePhong", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongResponse> GhiDuLieu_CapNhatPhieuThuePhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequest request);
        
        // CODEGEN: Generating message contract since element name DocDuLieu_GiaThuePhongResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_GiaThuePhong", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongResponse DocDuLieu_GiaThuePhong(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocDuLieu_GiaThuePhong", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongResponse> DocDuLieu_GiaThuePhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequest request);
        
        // CODEGEN: Generating message contract since element name ChuoiXml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GhiDuLieu_GiaThuePhong", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongResponse GhiDuLieu_GiaThuePhong(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GhiDuLieu_GiaThuePhong", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongResponse> GhiDuLieu_GiaThuePhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequest request);
        
        // CODEGEN: Generating message contract since element name Ma_so from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocHinh", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhResponse DocHinh(UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocHinh", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhResponse> DocHinhAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequest request);
        
        // CODEGEN: Generating message contract since element name Ma_so from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GhiHinh", ReplyAction="*")]
        UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhResponse GhiHinh(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GhiHinh", ReplyAction="*")]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhResponse> GhiHinhAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraCuuPhieuThuePhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraCuuPhieuThuePhong", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequestBody Body;
        
        public TraCuuPhieuThuePhongRequest() {
        }
        
        public TraCuuPhieuThuePhongRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraCuuPhieuThuePhongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChuoiXmlTruyVan;
        
        public TraCuuPhieuThuePhongRequestBody() {
        }
        
        public TraCuuPhieuThuePhongRequestBody(string ChuoiXmlTruyVan) {
            this.ChuoiXmlTruyVan = ChuoiXmlTruyVan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraCuuPhieuThuePhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraCuuPhieuThuePhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongResponseBody Body;
        
        public TraCuuPhieuThuePhongResponse() {
        }
        
        public TraCuuPhieuThuePhongResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraCuuPhieuThuePhongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TraCuuPhieuThuePhongResult;
        
        public TraCuuPhieuThuePhongResponseBody() {
        }
        
        public TraCuuPhieuThuePhongResponseBody(string TraCuuPhieuThuePhongResult) {
            this.TraCuuPhieuThuePhongResult = TraCuuPhieuThuePhongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_PhieuThuePhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_PhieuThuePhong", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequestBody Body;
        
        public DocDuLieu_PhieuThuePhongRequest() {
        }
        
        public DocDuLieu_PhieuThuePhongRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DocDuLieu_PhieuThuePhongRequestBody {
        
        public DocDuLieu_PhieuThuePhongRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_PhieuThuePhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_PhieuThuePhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongResponseBody Body;
        
        public DocDuLieu_PhieuThuePhongResponse() {
        }
        
        public DocDuLieu_PhieuThuePhongResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DocDuLieu_PhieuThuePhongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocDuLieu_PhieuThuePhongResult;
        
        public DocDuLieu_PhieuThuePhongResponseBody() {
        }
        
        public DocDuLieu_PhieuThuePhongResponseBody(string DocDuLieu_PhieuThuePhongResult) {
            this.DocDuLieu_PhieuThuePhongResult = DocDuLieu_PhieuThuePhongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_DangNhap_TiepTanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_DangNhap_TiepTan", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequestBody Body;
        
        public DocDuLieu_DangNhap_TiepTanRequest() {
        }
        
        public DocDuLieu_DangNhap_TiepTanRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DocDuLieu_DangNhap_TiepTanRequestBody {
        
        public DocDuLieu_DangNhap_TiepTanRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_DangNhap_TiepTanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_DangNhap_TiepTanResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanResponseBody Body;
        
        public DocDuLieu_DangNhap_TiepTanResponse() {
        }
        
        public DocDuLieu_DangNhap_TiepTanResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DocDuLieu_DangNhap_TiepTanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocDuLieu_DangNhap_TiepTanResult;
        
        public DocDuLieu_DangNhap_TiepTanResponseBody() {
        }
        
        public DocDuLieu_DangNhap_TiepTanResponseBody(string DocDuLieu_DangNhap_TiepTanResult) {
            this.DocDuLieu_DangNhap_TiepTanResult = DocDuLieu_DangNhap_TiepTanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_DangNhap_QLKhuVucRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_DangNhap_QLKhuVuc", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequestBody Body;
        
        public DocDuLieu_DangNhap_QLKhuVucRequest() {
        }
        
        public DocDuLieu_DangNhap_QLKhuVucRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DocDuLieu_DangNhap_QLKhuVucRequestBody {
        
        public DocDuLieu_DangNhap_QLKhuVucRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_DangNhap_QLKhuVucResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_DangNhap_QLKhuVucResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucResponseBody Body;
        
        public DocDuLieu_DangNhap_QLKhuVucResponse() {
        }
        
        public DocDuLieu_DangNhap_QLKhuVucResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DocDuLieu_DangNhap_QLKhuVucResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocDuLieu_DangNhap_QLKhuVucResult;
        
        public DocDuLieu_DangNhap_QLKhuVucResponseBody() {
        }
        
        public DocDuLieu_DangNhap_QLKhuVucResponseBody(string DocDuLieu_DangNhap_QLKhuVucResult) {
            this.DocDuLieu_DangNhap_QLKhuVucResult = DocDuLieu_DangNhap_QLKhuVucResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_DangNhap_QLKhachSanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_DangNhap_QLKhachSan", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequestBody Body;
        
        public DocDuLieu_DangNhap_QLKhachSanRequest() {
        }
        
        public DocDuLieu_DangNhap_QLKhachSanRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DocDuLieu_DangNhap_QLKhachSanRequestBody {
        
        public DocDuLieu_DangNhap_QLKhachSanRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_DangNhap_QLKhachSanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_DangNhap_QLKhachSanResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanResponseBody Body;
        
        public DocDuLieu_DangNhap_QLKhachSanResponse() {
        }
        
        public DocDuLieu_DangNhap_QLKhachSanResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DocDuLieu_DangNhap_QLKhachSanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocDuLieu_DangNhap_QLKhachSanResult;
        
        public DocDuLieu_DangNhap_QLKhachSanResponseBody() {
        }
        
        public DocDuLieu_DangNhap_QLKhachSanResponseBody(string DocDuLieu_DangNhap_QLKhachSanResult) {
            this.DocDuLieu_DangNhap_QLKhachSanResult = DocDuLieu_DangNhap_QLKhachSanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_ThongTinPhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_ThongTinPhong", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequestBody Body;
        
        public DocDuLieu_ThongTinPhongRequest() {
        }
        
        public DocDuLieu_ThongTinPhongRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DocDuLieu_ThongTinPhongRequestBody {
        
        public DocDuLieu_ThongTinPhongRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_ThongTinPhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_ThongTinPhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongResponseBody Body;
        
        public DocDuLieu_ThongTinPhongResponse() {
        }
        
        public DocDuLieu_ThongTinPhongResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DocDuLieu_ThongTinPhongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocDuLieu_ThongTinPhongResult;
        
        public DocDuLieu_ThongTinPhongResponseBody() {
        }
        
        public DocDuLieu_ThongTinPhongResponseBody(string DocDuLieu_ThongTinPhongResult) {
            this.DocDuLieu_ThongTinPhongResult = DocDuLieu_ThongTinPhongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_ThongKeDoanhThuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_ThongKeDoanhThu", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequestBody Body;
        
        public DocDuLieu_ThongKeDoanhThuRequest() {
        }
        
        public DocDuLieu_ThongKeDoanhThuRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DocDuLieu_ThongKeDoanhThuRequestBody {
        
        public DocDuLieu_ThongKeDoanhThuRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_ThongKeDoanhThuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_ThongKeDoanhThuResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuResponseBody Body;
        
        public DocDuLieu_ThongKeDoanhThuResponse() {
        }
        
        public DocDuLieu_ThongKeDoanhThuResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DocDuLieu_ThongKeDoanhThuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocDuLieu_ThongKeDoanhThuResult;
        
        public DocDuLieu_ThongKeDoanhThuResponseBody() {
        }
        
        public DocDuLieu_ThongKeDoanhThuResponseBody(string DocDuLieu_ThongKeDoanhThuResult) {
            this.DocDuLieu_ThongKeDoanhThuResult = DocDuLieu_ThongKeDoanhThuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GhiDuLieu_CapNhatPhieuThuePhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GhiDuLieu_CapNhatPhieuThuePhong", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequestBody Body;
        
        public GhiDuLieu_CapNhatPhieuThuePhongRequest() {
        }
        
        public GhiDuLieu_CapNhatPhieuThuePhongRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GhiDuLieu_CapNhatPhieuThuePhongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChuoiPhieuThue_;
        
        public GhiDuLieu_CapNhatPhieuThuePhongRequestBody() {
        }
        
        public GhiDuLieu_CapNhatPhieuThuePhongRequestBody(string ChuoiPhieuThue_) {
            this.ChuoiPhieuThue_ = ChuoiPhieuThue_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GhiDuLieu_CapNhatPhieuThuePhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GhiDuLieu_CapNhatPhieuThuePhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongResponseBody Body;
        
        public GhiDuLieu_CapNhatPhieuThuePhongResponse() {
        }
        
        public GhiDuLieu_CapNhatPhieuThuePhongResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GhiDuLieu_CapNhatPhieuThuePhongResponseBody {
        
        public GhiDuLieu_CapNhatPhieuThuePhongResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_GiaThuePhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_GiaThuePhong", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequestBody Body;
        
        public DocDuLieu_GiaThuePhongRequest() {
        }
        
        public DocDuLieu_GiaThuePhongRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DocDuLieu_GiaThuePhongRequestBody {
        
        public DocDuLieu_GiaThuePhongRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocDuLieu_GiaThuePhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocDuLieu_GiaThuePhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongResponseBody Body;
        
        public DocDuLieu_GiaThuePhongResponse() {
        }
        
        public DocDuLieu_GiaThuePhongResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DocDuLieu_GiaThuePhongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocDuLieu_GiaThuePhongResult;
        
        public DocDuLieu_GiaThuePhongResponseBody() {
        }
        
        public DocDuLieu_GiaThuePhongResponseBody(string DocDuLieu_GiaThuePhongResult) {
            this.DocDuLieu_GiaThuePhongResult = DocDuLieu_GiaThuePhongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GhiDuLieu_GiaThuePhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GhiDuLieu_GiaThuePhong", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequestBody Body;
        
        public GhiDuLieu_GiaThuePhongRequest() {
        }
        
        public GhiDuLieu_GiaThuePhongRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GhiDuLieu_GiaThuePhongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChuoiXml;
        
        public GhiDuLieu_GiaThuePhongRequestBody() {
        }
        
        public GhiDuLieu_GiaThuePhongRequestBody(string ChuoiXml) {
            this.ChuoiXml = ChuoiXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GhiDuLieu_GiaThuePhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GhiDuLieu_GiaThuePhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongResponseBody Body;
        
        public GhiDuLieu_GiaThuePhongResponse() {
        }
        
        public GhiDuLieu_GiaThuePhongResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GhiDuLieu_GiaThuePhongResponseBody {
        
        public GhiDuLieu_GiaThuePhongResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocHinhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocHinh", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequestBody Body;
        
        public DocHinhRequest() {
        }
        
        public DocHinhRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DocHinhRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ma_so;
        
        public DocHinhRequestBody() {
        }
        
        public DocHinhRequestBody(string Ma_so) {
            this.Ma_so = Ma_so;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocHinhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocHinhResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhResponseBody Body;
        
        public DocHinhResponse() {
        }
        
        public DocHinhResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DocHinhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DocHinhResult;
        
        public DocHinhResponseBody() {
        }
        
        public DocHinhResponseBody(byte[] DocHinhResult) {
            this.DocHinhResult = DocHinhResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GhiHinhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GhiHinh", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequestBody Body;
        
        public GhiHinhRequest() {
        }
        
        public GhiHinhRequest(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GhiHinhRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ma_so;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] Nhi_phan_Hinh;
        
        public GhiHinhRequestBody() {
        }
        
        public GhiHinhRequestBody(string Ma_so, byte[] Nhi_phan_Hinh) {
            this.Ma_so = Ma_so;
            this.Nhi_phan_Hinh = Nhi_phan_Hinh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GhiHinhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GhiHinhResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhResponseBody Body;
        
        public GhiHinhResponse() {
        }
        
        public GhiHinhResponse(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GhiHinhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GhiHinhResult;
        
        public GhiHinhResponseBody() {
        }
        
        public GhiHinhResponseBody(string GhiHinhResult) {
            this.GhiHinhResult = GhiHinhResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DICHVU_ASMXSoapChannel : UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DICHVU_ASMXSoapClient : System.ServiceModel.ClientBase<UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap>, UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap {
        
        public DICHVU_ASMXSoapClient() {
        }
        
        public DICHVU_ASMXSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DICHVU_ASMXSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DICHVU_ASMXSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DICHVU_ASMXSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.TraCuuPhieuThuePhong(UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequest request) {
            return base.Channel.TraCuuPhieuThuePhong(request);
        }
        
        public string TraCuuPhieuThuePhong(string ChuoiXmlTruyVan) {
            UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequestBody();
            inValue.Body.ChuoiXmlTruyVan = ChuoiXmlTruyVan;
            UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).TraCuuPhieuThuePhong(inValue);
            return retVal.Body.TraCuuPhieuThuePhongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.TraCuuPhieuThuePhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequest request) {
            return base.Channel.TraCuuPhieuThuePhongAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongResponse> TraCuuPhieuThuePhongAsync(string ChuoiXmlTruyVan) {
            UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.TraCuuPhieuThuePhongRequestBody();
            inValue.Body.ChuoiXmlTruyVan = ChuoiXmlTruyVan;
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).TraCuuPhieuThuePhongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_PhieuThuePhong(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequest request) {
            return base.Channel.DocDuLieu_PhieuThuePhong(request);
        }
        
        public string DocDuLieu_PhieuThuePhong() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequestBody();
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_PhieuThuePhong(inValue);
            return retVal.Body.DocDuLieu_PhieuThuePhongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_PhieuThuePhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequest request) {
            return base.Channel.DocDuLieu_PhieuThuePhongAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongResponse> DocDuLieu_PhieuThuePhongAsync() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_PhieuThuePhongRequestBody();
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_PhieuThuePhongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_DangNhap_TiepTan(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequest request) {
            return base.Channel.DocDuLieu_DangNhap_TiepTan(request);
        }
        
        public string DocDuLieu_DangNhap_TiepTan() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequestBody();
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_DangNhap_TiepTan(inValue);
            return retVal.Body.DocDuLieu_DangNhap_TiepTanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_DangNhap_TiepTanAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequest request) {
            return base.Channel.DocDuLieu_DangNhap_TiepTanAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanResponse> DocDuLieu_DangNhap_TiepTanAsync() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_TiepTanRequestBody();
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_DangNhap_TiepTanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_DangNhap_QLKhuVuc(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequest request) {
            return base.Channel.DocDuLieu_DangNhap_QLKhuVuc(request);
        }
        
        public string DocDuLieu_DangNhap_QLKhuVuc() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequestBody();
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_DangNhap_QLKhuVuc(inValue);
            return retVal.Body.DocDuLieu_DangNhap_QLKhuVucResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_DangNhap_QLKhuVucAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequest request) {
            return base.Channel.DocDuLieu_DangNhap_QLKhuVucAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucResponse> DocDuLieu_DangNhap_QLKhuVucAsync() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhuVucRequestBody();
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_DangNhap_QLKhuVucAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_DangNhap_QLKhachSan(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequest request) {
            return base.Channel.DocDuLieu_DangNhap_QLKhachSan(request);
        }
        
        public string DocDuLieu_DangNhap_QLKhachSan() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequestBody();
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_DangNhap_QLKhachSan(inValue);
            return retVal.Body.DocDuLieu_DangNhap_QLKhachSanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_DangNhap_QLKhachSanAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequest request) {
            return base.Channel.DocDuLieu_DangNhap_QLKhachSanAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanResponse> DocDuLieu_DangNhap_QLKhachSanAsync() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_DangNhap_QLKhachSanRequestBody();
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_DangNhap_QLKhachSanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_ThongTinPhong(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequest request) {
            return base.Channel.DocDuLieu_ThongTinPhong(request);
        }
        
        public string DocDuLieu_ThongTinPhong() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequestBody();
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_ThongTinPhong(inValue);
            return retVal.Body.DocDuLieu_ThongTinPhongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_ThongTinPhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequest request) {
            return base.Channel.DocDuLieu_ThongTinPhongAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongResponse> DocDuLieu_ThongTinPhongAsync() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongTinPhongRequestBody();
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_ThongTinPhongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_ThongKeDoanhThu(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequest request) {
            return base.Channel.DocDuLieu_ThongKeDoanhThu(request);
        }
        
        public string DocDuLieu_ThongKeDoanhThu() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequestBody();
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_ThongKeDoanhThu(inValue);
            return retVal.Body.DocDuLieu_ThongKeDoanhThuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_ThongKeDoanhThuAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequest request) {
            return base.Channel.DocDuLieu_ThongKeDoanhThuAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuResponse> DocDuLieu_ThongKeDoanhThuAsync() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_ThongKeDoanhThuRequestBody();
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_ThongKeDoanhThuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.GhiDuLieu_CapNhatPhieuThuePhong(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequest request) {
            return base.Channel.GhiDuLieu_CapNhatPhieuThuePhong(request);
        }
        
        public void GhiDuLieu_CapNhatPhieuThuePhong(string ChuoiPhieuThue_) {
            UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequestBody();
            inValue.Body.ChuoiPhieuThue_ = ChuoiPhieuThue_;
            UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).GhiDuLieu_CapNhatPhieuThuePhong(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.GhiDuLieu_CapNhatPhieuThuePhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequest request) {
            return base.Channel.GhiDuLieu_CapNhatPhieuThuePhongAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongResponse> GhiDuLieu_CapNhatPhieuThuePhongAsync(string ChuoiPhieuThue_) {
            UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_CapNhatPhieuThuePhongRequestBody();
            inValue.Body.ChuoiPhieuThue_ = ChuoiPhieuThue_;
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).GhiDuLieu_CapNhatPhieuThuePhongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_GiaThuePhong(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequest request) {
            return base.Channel.DocDuLieu_GiaThuePhong(request);
        }
        
        public string DocDuLieu_GiaThuePhong() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequestBody();
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_GiaThuePhong(inValue);
            return retVal.Body.DocDuLieu_GiaThuePhongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocDuLieu_GiaThuePhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequest request) {
            return base.Channel.DocDuLieu_GiaThuePhongAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongResponse> DocDuLieu_GiaThuePhongAsync() {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocDuLieu_GiaThuePhongRequestBody();
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocDuLieu_GiaThuePhongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.GhiDuLieu_GiaThuePhong(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequest request) {
            return base.Channel.GhiDuLieu_GiaThuePhong(request);
        }
        
        public void GhiDuLieu_GiaThuePhong(string ChuoiXml) {
            UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequestBody();
            inValue.Body.ChuoiXml = ChuoiXml;
            UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).GhiDuLieu_GiaThuePhong(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.GhiDuLieu_GiaThuePhongAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequest request) {
            return base.Channel.GhiDuLieu_GiaThuePhongAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongResponse> GhiDuLieu_GiaThuePhongAsync(string ChuoiXml) {
            UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiDuLieu_GiaThuePhongRequestBody();
            inValue.Body.ChuoiXml = ChuoiXml;
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).GhiDuLieu_GiaThuePhongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocHinh(UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequest request) {
            return base.Channel.DocHinh(request);
        }
        
        public byte[] DocHinh(string Ma_so) {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequestBody();
            inValue.Body.Ma_so = Ma_so;
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocHinh(inValue);
            return retVal.Body.DocHinhResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.DocHinhAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequest request) {
            return base.Channel.DocHinhAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhResponse> DocHinhAsync(string Ma_so) {
            UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.DocHinhRequestBody();
            inValue.Body.Ma_so = Ma_so;
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).DocHinhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhResponse UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.GhiHinh(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequest request) {
            return base.Channel.GhiHinh(request);
        }
        
        public string GhiHinh(string Ma_so, byte[] Nhi_phan_Hinh) {
            UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequestBody();
            inValue.Body.Ma_so = Ma_so;
            inValue.Body.Nhi_phan_Hinh = Nhi_phan_Hinh;
            UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhResponse retVal = ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).GhiHinh(inValue);
            return retVal.Body.GhiHinhResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhResponse> UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap.GhiHinhAsync(UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequest request) {
            return base.Channel.GhiHinhAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhResponse> GhiHinhAsync(string Ma_so, byte[] Nhi_phan_Hinh) {
            UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequest inValue = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequest();
            inValue.Body = new UngdungWeb_KhachHang.DICHVU_ASMX_.GhiHinhRequestBody();
            inValue.Body.Ma_so = Ma_so;
            inValue.Body.Nhi_phan_Hinh = Nhi_phan_Hinh;
            return ((UngdungWeb_KhachHang.DICHVU_ASMX_.DICHVU_ASMXSoap)(this)).GhiHinhAsync(inValue);
        }
    }
}
